### ISSUE TITLE
Requires Double Tap to Play Video in Mobile

### ISSUE THREAD

**Issue by parth-khiera** [danestves/react-youtube-lite#95]
To start video, requires double tap in mobile browser, 
1. to initiate iframe and 
2. to start actual video

Also Auto play seems not working as, there is no way to pass mute option.

**Comment by danestves** [comment]
Hi, that is because YouTube embed doesn't autoplay on mobile, so if you want to force it, you need to use this parameter https://developers.google.com/youtube/player_parameters#playsinline
